# Site settings
title: All Free Tricks
description: > 
  Welcome to All Free Tricks, Here you will get all internet and mobile recharge offers, coupons, app rewards any many more tricks. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.allfreetricks.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: none

include: ['_pages']

gems:
  - jekyll-redirect-from
  
  
