# Site settings
title: All Free Tricks
description: > 
  Here you will get all type of Free Tricks including Mobile Recharge Tricks, Apps Rewards, Free Internet and Computer Tricks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.allfreetricks.com" # the base hostname & protocol for your site

# Build settings
highlighter: pygments
permalink: none

include: ['_pages']

gems:
  - jekyll-redirect-from
  
  
